name: Daily Article Fetch

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  fetch_articles:
    runs-on: ubuntu-latest
    environment: mavka

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv and dependencies
      run: |
        pip install uv
        uv pip install --system

    - name: Run fetch script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        python main.py
