name: Daily Article Fetch

on:
  schedule:
    - cron: '0 9 * * *'  # щоденно о 09:00 UTC
  workflow_dispatch:     # щоб запускати вручну з UI GitHub

jobs:
  fetch_articles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run fetch script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        python main.py
